choco install intellijidea-community -y
choco install microsoft-windows-terminal -y
choco install pycharm-community -y
choco install vscode -y
choco install nodejs -y
choco install awscli -y
choco install curl -y
choco install git -y
choco install adoptopenjdk -y
choco install maven -y
choco install gradle -y
choco install docker-cli -y
choco install dbeaver -y
